server:
  port: 8601
spring:
  application:
    name: web-customer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.12:8848
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: basic
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


