server:
  port: 8600
feign:
  sentinel:
    enabled: true
spring:
  application:
    name: leshang-daijia-20260104
  datasource:
    url: jdbc:mysql://localhost:3306/daijia_customer?serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: basic


jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 24


