version: '3.8'

networks:
  daijia-net:
    external: true  # 使用中间件的网络

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: leshang-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - daijia-net  # 加入同一网络



volumes:
  prometheus_data:
