apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://leshang-prometheus:9090
    isDefault: true
    editable: true

# prometheus.yml 改用服务发现
scrape_configs:
  - job_name: 'server-gateway'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'server-gateway'
        type: 'A'
        port: 8600

